%---------------------------------------------------------------------------------------------------
% template document
\documentclass[12pt, a4paper, twoside, openright, openany]{book}
\input{\Sexpr{REP$style}}
\input{\Sexpr{REP$style_math}}

%---------------------------------------------------------------------------------------------------
%\SetWatermarkText{\Sexpr{REP$watermark}}
\SetWatermarkText{}
\SetWatermarkScale{0.40}
\SetWatermarkColor[gray]{0.7}


% Bibliografía -------------------------------------------------------------------------------------
\addbibresource{\Sexpr{REP$bib_lib}}
\addbibresource{\Sexpr{REP$bib_art}}
\addbibresource{\Sexpr{REP$bib_ley}}

%---------------------------------------------------------------------------------------------------
% Inicio del documento
\begin{document}

%---------------------------------------------------------------------------------------------------
%\frontmatter
% Contenidos
<<cap01, child='01_cobertura.Rnw'>>=
@

%<<cap02, child='02_contenido.Rnw'>>=
%@

%---------------------------------------------------------------------------------------------------
% Cuerpo del estudio
\mainmatter

% <<cap03, child='03_resumen_ejecutivo.Rnw'>>=
% @
% 
%<<cap04, child='04_antecedentes.Rnw'>>=
%@
%  
%<<cap05, child='05_base_legal.Rnw'>>=
%@
% 
% <<cap06, child='06_analisis_contexto.Rnw'>>=
% @
%  
%<<cap07, child='07_demografia.Rnw'>>=
%@
%  
% <<cap08, child='08_inversiones.Rnw'>>=
% @
%   
% <<cap09, child='09_demografia.Rnw'>>=
% @
%    
% <<cap10, child='10_metodologia.Rnw'>>=
% @
%    
% <<cap11, child='11_hipotesis.Rnw'>>=
% @ 
%    
% <<cap12, child='12_riesgos.Rnw'>>=
% @
%   
% <<cap13, child='13_situacion.Rnw'>>=
% @
% 
% <<cap14, child='14_sensibilidad.Rnw'>>=
% @
% 
% <<cap15, child='15_conclusion.Rnw'>>=
% @
%  
% <<cap16, child='16_opinion_actuarial.Rnw'>>=
% @

%---------------------------------------------------------------------------------------------------
% Apéndices
\appendix
%\appendixpage

% <<cap16, child='16_anx_modelo_macro.Rnw'>>=
% @

% <<cap17, child='17_anx_tasas_morbilidad.Rnw'>>=
% @

% <<cap18, child='18_anx_tablas_biometricas.Rnw'>>=
% @

%<<cap20, child='20_anx_copia_optica.Rnw'>>=
%@

%---------------------------------------------------------------------------------------------------
% Acrónimos
%<<cap21, child='21_anx_acronimos.Rnw'>>=
%@

%<<cap16, child='18_anexos.Rnw'>>=
%@

%---------------------------------------------------------------------------------------------------
%\backmatter

% Bibliografía
\printbibliography
\addcontentsline{toc}{chapter}{Bibliografía}

\end{document}
