# Carga de paquetes --------------------------------------------------------------------------------
message( paste( rep( '-', 100 ), collapse = '' ) )
message( '\tCargando paquetes' )

suppressPackageStartupMessages( library( actuar ) )
suppressPackageStartupMessages( library( chron ) )
suppressPackageStartupMessages( library( colorRamps ) )
suppressPackageStartupMessages( library( compiler ) )
suppressPackageStartupMessages( library( data.table ) )
suppressPackageStartupMessages( library( DiceKriging ) )
suppressPackageStartupMessages( library( digest ) )
suppressPackageStartupMessages( library( doParallel ) )
suppressPackageStartupMessages( library( dplyr, warn.conflicts = FALSE ) )
suppressPackageStartupMessages( library( dtplyr ) )
suppressPackageStartupMessages( library( eeptools ) )
suppressPackageStartupMessages( library( extrafont ) )
suppressPackageStartupMessages( library( fields ) )
suppressPackageStartupMessages( library( forecast ) )
suppressPackageStartupMessages( library( fUnitRoots ) )
suppressPackageStartupMessages( library( ggforce ) )
# suppressPackageStartupMessages( library( maptools ) )
suppressPackageStartupMessages( library( ggfortify ) )  # for plotting timeseries
suppressPackageStartupMessages( library( ggmap ) )
suppressPackageStartupMessages( library( ggplot2 ) )
suppressPackageStartupMessages( library( gplots ) )
suppressPackageStartupMessages( library( ggpubr ) )
suppressPackageStartupMessages( library( ggrepel ) )
suppressPackageStartupMessages( library( ggthemes ) )
suppressPackageStartupMessages( library( grid ) )
suppressPackageStartupMessages( library( gridExtra ) )
suppressPackageStartupMessages( library( gstat) )
suppressPackageStartupMessages( library( Hmisc ) )
suppressPackageStartupMessages( library( imputeTS ) )
suppressPackageStartupMessages( library( janitor ) )
suppressPackageStartupMessages( library( knitr ) )
# suppressPackageStartupMessages( library( ks ) )
suppressPackageStartupMessages( library( latex2exp ) )
suppressPackageStartupMessages( library( lattice ) )
suppressPackageStartupMessages( library( lmtest ) )
suppressPackageStartupMessages( library( lubridate ) )
suppressPackageStartupMessages( library( magick ) )
suppressPackageStartupMessages( library( mapproj ) )
suppressPackageStartupMessages( library( marima ) )
suppressPackageStartupMessages( library( MASS ) )
suppressPackageStartupMessages( library( MTS ) )
suppressPackageStartupMessages( library( openxlsx ) )
suppressPackageStartupMessages( library( parallel ) )
suppressPackageStartupMessages( library( portes ) )
suppressPackageStartupMessages( library( ppcor ) )
suppressPackageStartupMessages( library( pracma ) )
suppressPackageStartupMessages( library( quadprog ) )
suppressPackageStartupMessages( library( readr ) )
suppressPackageStartupMessages( library( readxl ) )
suppressPackageStartupMessages( library( reshape2 ) )
suppressPackageStartupMessages( library( RColorBrewer ) )
suppressPackageStartupMessages( library( RcppParallel ) )
suppressPackageStartupMessages( library( RcppRoll ) )
suppressPackageStartupMessages( library( rgl ) )
# suppressPackageStartupMessages( library( RJDBC ) )
suppressPackageStartupMessages( library( scales ) )
suppressPackageStartupMessages( library( showtext ) )
suppressPackageStartupMessages( library( splines ) )
suppressPackageStartupMessages( library( smoots ) )
suppressPackageStartupMessages( library( stargazer ) )
suppressPackageStartupMessages( library( stringr ) )
suppressPackageStartupMessages( library( sysfonts ) )
suppressPackageStartupMessages( library( tidymodels ) )
suppressPackageStartupMessages( library( tidyposterior ) )
suppressPackageStartupMessages( library( tidyr ) )
suppressPackageStartupMessages( library( tidyverse ) )
suppressPackageStartupMessages( library( treemapify ) )
suppressPackageStartupMessages( library( vars ) )
suppressPackageStartupMessages( library( weakARMA ) )
suppressPackageStartupMessages( library( xtable ) )
suppressPackageStartupMessages( library( zoo ) )

# extrafont::font_import()
suppressMessages( loadfonts() )

message( paste( rep( '-', 100 ), collapse = '' ) )